github-repo: "https://github.com/spring-projects/spring-restdocs.git"
github-repo-name: "spring-projects/spring-restdocs"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "main"
milestone: "2.0.x"
build-name: "spring-restdocs"
concourse-url: "https://ci.spring.io"
task-timeout: 1h00m
