github-organization: "spring-projects"
github-repository: "spring-restdocs"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "2.0.x"
milestone: "2.0.x"
build-name: "spring-restdocs"
concourse-url: "https://ci.spring.io"
task-timeout: 1h00m
registry-mirror-host: docker.repo.spring.io
registry-mirror-username: ((artifactory-username))
registry-mirror-password: ((artifactory-password))